name: migrant
version: 0.0.8
description: A simple database schema migration tool
homepage: "https://github.com/f3ath/migrant"

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  check_coverage: ^0.0.4
  cider: ^0.1.0
  migrant_source_fs: ^0.0.2
  migrant_db_sqlite: ^0.0.1
  sqflite_common_ffi: ^2.1.1

cider:
  link_template:
    tag: https://github.com/f3ath/migrant/releases/tag/%tag%
    diff: https://github.com/f3ath/migrant/compare/%from%...%to%