name: migrant
version: 0.3.0
description: A simple database schema migration tool. Supports SQLite and PostgreSQL, can read migration scripts from multiple sources.
homepage: "https://github.com/f3ath/migrant"

environment:
  sdk: '>=3.5.0 <4.0.0'

dev_dependencies:
  lints: ">=4.0.0 <7.0.0"
  test: ^1.20.1
  check_coverage: ^0.0.4
  cider: ^0.2.7

cider:
  link_template:
    tag: https://github.com/f3ath/migrant/releases/tag/%tag%
    diff: https://github.com/f3ath/migrant/compare/%from%...%to%